<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- 22-Nov-2011 AYA : BDT 26587 update profile for the Jenkins build. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.thevpc.xprojects.builders</groupId>
    <artifactId>ntexup-builder</artifactId>
    <name>ntexup :: All Builder</name>
    <version>0.8.8.0</version>
    <packaging>pom</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <modules>
        <module>core/ntexup-api</module>
        <module>core/ntexup-engine</module>
        <module>test/ntexup-examples</module>
        <module>extensions/ntexup-extension-plantuml</module>
        <module>extensions/ntexup-extension-animated-gif</module>
        <module>extensions/ntexup-extension-svg</module>
        <module>extensions/ntexup-extension-shapes2d</module>
        <module>extensions/ntexup-extension-shapes3d</module>
        <module>extensions/ntexup-extension-plot2d</module>
        <module>extensions/ntexup-extension-latex</module>
        <module>extensions/ntexup-extension-presenters</module>
        <module>tutorials/ntexup-extension-tutorial-myshape</module>
        <module>companions/nscoreboard</module>
        <module>renderers/ntexup-renderer-pdf</module>
        <module>renderers/ntexup-renderer-html</module>
        <module>renderers/ntexup-renderer-screen</module>
        <module>renderers/ntexup-renderer-web</module>
        <module>app/ntexup</module>
        <module>app/ntexup-viewer-backend</module>
        <module>ntexup-full</module>
    </modules>
</project>
